### ISSUE TITLE
Don't run

### ISSUE THREAD

**Issue by rufisayev** [Tiagojdferreira/rn-geolocation#5]
Hello,i clone this example and my "react-native run-android" successfully build and install my app. But when i try to open program it gets error like this "unable to download JS bundle".What can i do?

**Comment by cosmith** [comment]
Did you check this? http://facebook.github.io/react-native/docs/running-on-device-android.html#content

Also you probably don't need this package anymore since Geolocation was open-sourced on Android: http://facebook.github.io/react-native/docs/geolocation.html#content

**Comment by tiagojdf** [comment]
Closing this has you should use React native 0.15 or + instead of this package.
